# Generated by Django 5.2 on 2025-05-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='processed_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
