# Generated by Django 5.2 on 2025-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_uploadedfile_processed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
