# Generated by Django 5.2 on 2025-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploadedfile_processed_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='processed_data_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
