# Generated by Django 5.2 on 2025-05-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_uploadedfile_processed_data_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='processed_data_json',
            new_name='json_data',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='processed_data',
            new_name='markdown_data',
        ),
    ]
